### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by ayeletda** [ayeletda/TenPartners#2]
Documet: [SRS](https://github.com/ayeletda/TenPartners/wiki/srs)
Code: [:computer:](https://github.com/ayeletda/TenPartners/tree/master/TenPartnersApp)

**Comment by robi-y** [comment]
Are you done with this task? Please don't assign @kob-e before you finish.
Also, edit the issue (text) above to match the assignment

**Comment by ayeletda** [comment]
OK, we didn't know we shouldn't do it.

**Comment by kob-e** [comment]
Feedback at #7
