### ISSUE TITLE
Changing the date of the project

### ISSUE THREAD

**Issue by Avia-Cheriker** [ayeletda/TenPartners#21]
**The user-story:**
As the main administrator I would like to be able to change the date of the projects which I own so that I can change the date if there was a problem on the previous date.

**Test scenarios:**
1. Going to the list of projects I own and clicking the appropriate button for changing the date of project.
2. Filling the appropriate field and clicking "OK" button 

**Expected results:** 
1. A field to enter the new date appears.
2. The date was changed

**Comment by robi-y** [comment]
So that the correct date is tracked...??
