### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by kob-e** [ayeletda/TenPartners#7]
## TODO:
- Please attach here the Client review.

## סיכום פגישתנו:
חסר סיכונים

**Comment by ayeletda** [comment]
Done!

[The client review](https://github.com/ayeletda/TenPartners/wiki/srs#the-client-review)

**Comment by kob-e** [comment]
יפה

**Comment by kob-e** [comment]
risk attached:
The main risk in our project is compliance with client requirements. Our client has specific and well defined requirements. He knew what he wanted from the beginning and he expects us to stand in them. we will handle with this risk by a deeper and tighter surveillance. The foundations' prototype we built made us understand the parts of the system that we have to deal with in order to qualify. Charts help us understand wich classes we will need and which platforms we will use. The statecharts help us to disassemble the requirements for details and we will confront them with the client in order to get to the depth of his wishes.
